#!/usr/bin/env bash
#
# Display a list of currently running processes (the simple BSD way)

#PS_FORMAT='user,pid,%cpu,%mem,vsz,rss,tty,stat,start_time,bsdtime,args' ps -e --forest --sort=user

ps auxf
