#!/usr/bin/env bash
#
# Display login name, uid, and home directory for each account in /etc/passwd
# Account format is <login>:<password>:<uid>:<gid>:<name>:<home>:<shell>
# Also see passwd(5)

while IFS=':' read -r login _ uid _ _ home _
do
    printf '%s:%s:%s\n' "${login}" "${uid}" "${home}"
done </etc/passwd
