#!/usr/bin/env bash
#
# Tell the story of each account in /etc/passwd
# Account format is <login>:<password>:<uid>:<gid>:<name>:<home>:<shell>
# Also see passwd(5)

storytime()
{
    cat
} <<@STOP
The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is \
protected by the passcode $2, more info about the user here: $5
@STOP

while IFS=':' read -ra account
do
    storytime "${account[@]}"
done </etc/passwd
